(() => {
  const phone = '573183502235';
  const wa = (message) => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

  const css = `
    @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap');
    :root{--ink:#183c2d;--paper:#f7f0e3;--sand:#e9e2d2;--gold:#d5b66f;--muted:#6d756d}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Manrope,Arial,sans-serif;-webkit-font-smoothing:antialiased}a{text-decoration:none;color:inherit}button{font:inherit;cursor:pointer}img{max-width:100%}.wrap{width:min(1180px,calc(100% - 48px));margin:auto}
    .top{position:absolute;z-index:3;inset:0 0 auto;border-bottom:1px solid #ffffff3b;color:#fff}.nav{height:86px;display:flex;align-items:center;justify-content:space-between}.brand img{width:160px;display:block;filter:brightness(1.3) saturate(.7);mix-blend-mode:screen}.links{display:flex;align-items:center;gap:30px;font-size:10px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.links a{padding:8px 0}.nav-cta,.primary{display:inline-flex;align-items:center;justify-content:center;gap:10px;border:0;border-radius:999px;background:var(--gold);color:var(--ink);padding:15px 22px;font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;transition:.25s}.nav-cta:hover,.primary:hover{transform:translateY(-3px);background:#e4c57e}.menu{display:none;border:0;background:transparent;color:#fff;font-size:23px}
    .hero{position:relative;min-height:880px;display:flex;align-items:flex-end;overflow:hidden;background:var(--ink);color:#fff}.hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.hero:after{position:absolute;inset:0;content:'';background:linear-gradient(90deg,#0a231dcc,#0a231d85 43%,#0a231d24),linear-gradient(0deg,#0a231db8,transparent 58%)}.hero-content{position:relative;z-index:1;width:min(1180px,calc(100% - 48px));margin:auto;padding:160px 0 125px}.eyebrow{color:var(--gold);font-size:10px;font-weight:800;letter-spacing:.24em;text-transform:uppercase}.hero h1,.title{font-family:'Cormorant Garamond',Georgia,serif;font-weight:500;letter-spacing:-.045em;line-height:.83}.hero h1{max-width:720px;margin:20px 0 25px;font-size:clamp(68px,10vw,130px)}.hero h1 em,.title em{color:var(--gold)}.hero p{max-width:450px;margin:0 0 34px;color:#fffdd7d6;font-size:15px;line-height:1.8}.actions{display:flex;gap:20px;align-items:center}.ghost{display:inline-flex;align-items:center;gap:10px;border:1px solid #fff8;padding:15px 22px;border-radius:999px;color:#fff;font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hero-foot{position:absolute;z-index:1;right:0;bottom:0;left:0;border-top:1px solid #ffffff3b}.hero-foot .wrap{display:flex;justify-content:space-between;padding:19px 0;color:#ffffffb8;font-size:9px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}
    section{padding:125px 0}.intro{background:var(--paper)}.intro-grid,.contact-grid,.location{display:grid;grid-template-columns:1fr 1fr;gap:100px;align-items:center}.title{margin:18px 0 0;font-size:clamp(52px,7vw,88px)}.copy{color:var(--muted);font-size:14px;line-height:1.9}.intro .copy{max-width:450px;margin-top:32px}.quote{border-left:1px solid var(--gold);padding:42px 0 42px 42px;font:500 clamp(34px,4vw,50px)/.97 'Cormorant Garamond',Georgia,serif}.quote small{display:block;margin-top:28px;color:var(--muted);font:800 10px/1.5 Manrope,sans-serif;letter-spacing:.14em;text-transform:uppercase}
    .stats{padding:0;background:var(--ink);color:#fff}.stats .wrap{display:grid;grid-template-columns:repeat(4,1fr)}.stat{min-height:180px;padding:30px;border-left:1px solid #d5b66f33}.stat strong{display:block;color:var(--gold);font:57px/.8 'Cormorant Garamond',Georgia,serif}.stat span{display:block;margin-top:18px;color:#fffbb3;font-size:10px;font-weight:800;letter-spacing:.12em;line-height:1.5;text-transform:uppercase}
    .experience{background:var(--sand)}.section-head{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:58px}.section-head>div:first-child{max-width:560px}.section-head .copy{max-width:350px;margin:0}.features{display:grid;grid-template-columns:1.25fr .75fr;gap:24px}.feature-stack{display:grid;gap:24px}.feature{position:relative;min-height:570px;overflow:hidden;background:var(--ink);color:#fff}.feature.small{min-height:273px}.feature img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transition:.6s}.feature:hover img{transform:scale(1.05)}.feature:after{position:absolute;inset:0;content:'';background:linear-gradient(0deg,#0b241dd9,transparent 65%)}.feature-copy{position:absolute;z-index:1;right:30px;bottom:28px;left:30px}.feature-copy small{color:var(--gold);font-size:10px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.feature-copy h3{margin:10px 0 0;font:500 42px/.9 'Cormorant Garamond',Georgia,serif}.small h3{font-size:32px}
    .amenities{background:var(--paper)}.amenity-layout{display:grid;grid-template-columns:.85fr 1.15fr;gap:100px}.amenity-list{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #cfc6b5}.amenity{min-height:150px;padding:24px 22px 20px 0;border-bottom:1px solid #cfc6b5}.amenity:nth-child(odd){border-right:1px solid #cfc6b5;padding-right:30px}.amenity:nth-child(even){padding-left:30px}.amenity b{display:grid;place-items:center;width:38px;height:38px;margin-bottom:15px;border:1px solid var(--gold);border-radius:50%;font-size:18px;font-weight:400}.amenity h3{margin:0 0 7px;font-size:13px}.amenity p{margin:0;color:var(--muted);font-size:11px;line-height:1.6}
    .plan{background:var(--ink);color:#fff}.plan-grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:90px;align-items:center}.plan .copy{margin:25px 0 32px;color:#fff9}.plan-frame{padding:18px;background:#eee9dd;transform:rotate(1.2deg);box-shadow:0 25px 55px #0003}.plan-frame img{display:block;width:100%}.caption{display:flex;justify-content:space-between;margin-top:22px;color:#fff9;font-size:9px;letter-spacing:.12em;text-transform:uppercase}
    .videos{background:var(--sand)}.slider{display:grid;grid-template-columns:1.45fr .55fr;background:var(--ink);color:#fff;box-shadow:0 25px 55px #183c2d24}.stage{position:relative;aspect-ratio:16/9;background:#102e24}.stage video{display:block;width:100%;height:100%;object-fit:cover}.badge{position:absolute;top:18px;left:18px;padding:9px 12px;background:#0a231db8;color:var(--gold);font-size:9px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.details{display:flex;min-height:100%;flex-direction:column;justify-content:space-between;padding:40px 36px 32px}.num{color:var(--gold);font:56px/.8 'Cormorant Garamond',Georgia,serif}.details h3{max-width:220px;margin:25px 0 12px;font:500 38px/.9 'Cormorant Garamond',Georgia,serif}.details p{max-width:220px;color:#fff9;font-size:11px;line-height:1.7}.controls{display:flex;align-items:center;justify-content:space-between;margin-top:30px}.controls button{display:grid;place-items:center;width:38px;height:38px;border:1px solid #fff8;border-radius:50%;background:transparent;color:#fff}.dots{display:flex;gap:8px}.dots button{width:26px;height:2px;padding:0;border:0;border-radius:0;background:#fff6}.dots button.active{width:42px;background:var(--gold)}
    .gallery{background:var(--paper)}.gallery-grid{display:grid;grid-template-columns:1.4fr .75fr .75fr;grid-template-rows:250px 250px;gap:16px}.gallery-item{position:relative;overflow:hidden;background:#c5bda9}.gallery-item:first-child{grid-row:1/3}.gallery-item img{width:100%;height:100%;object-fit:cover;transition:.6s}.gallery-item:hover img{transform:scale(1.06)}
    .location{gap:0;align-items:stretch;padding:0;background:#d8cdb7}.location-image{min-height:550px}.location-image img{width:100%;height:100%;object-fit:cover;mix-blend-mode:multiply;opacity:.75}.location-copy{display:flex;flex-direction:column;justify-content:center;padding:75px clamp(35px,8vw,120px) 75px 75px}.points{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding-top:25px;border-top:1px solid #183c2d2f}.point strong{display:block;font:600 20px 'Cormorant Garamond',Georgia,serif}.point span{display:block;margin-top:4px;color:var(--muted);font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}
    .contact{background:var(--gold)}.contact .title{max-width:500px}.contact .copy{max-width:380px;margin-top:25px;color:#183c2db8}.form{padding:30px;background:#faf3e3ad;border:1px solid #183c2d26}.form label{display:block;margin-bottom:7px;color:#183c2db8;font-size:9px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.form input,.form textarea{display:block;width:100%;margin-bottom:19px;padding:12px 0;border:0;border-bottom:1px solid #183c2d55;outline:0;background:transparent;color:var(--ink);font:14px Manrope,sans-serif}.form textarea{min-height:55px;resize:vertical}.form button{width:100%}.success{padding:20px;background:#faf3e3ad;border:1px solid #183c2d44;line-height:1.6}.success strong{display:block;margin-bottom:7px;font:600 28px 'Cormorant Garamond',Georgia,serif}
    footer{padding:35px 0;background:var(--ink);color:#fff}.footer-top{display:flex;justify-content:space-between;align-items:center;padding-bottom:30px;border-bottom:1px solid #fff3}.footer-logo{width:150px;filter:brightness(1.3) saturate(.7);mix-blend-mode:screen}.phone{color:var(--gold);font-size:14px;font-weight:800}.footer-bottom{display:flex;justify-content:space-between;padding-top:20px;color:#fff7;font-size:9px;letter-spacing:.08em}.float{position:fixed;z-index:5;right:24px;bottom:24px;padding:14px 19px;border:1px solid #183c2d20;border-radius:999px;background:var(--gold);color:var(--ink);box-shadow:0 13px 30px #0f271d38;font-size:10px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}
    @media(max-width:850px){.wrap,.hero-content{width:min(calc(100% - 38px),650px)}.nav{height:72px}.brand img{width:135px}.menu{display:block}.links{position:absolute;top:71px;left:19px;right:19px;display:none;flex-direction:column;align-items:stretch;gap:0;padding:10px 20px;background:#0f2c21f7;border:1px solid #fff3}.links.open{display:flex}.links a{padding:14px 0;border-bottom:1px solid #fff2}.nav-cta{margin:10px 0 8px;text-align:center}.hero{min-height:760px}.hero-content{padding-bottom:120px}.intro-grid,.contact-grid,.amenity-layout,.plan-grid{grid-template-columns:1fr;gap:55px}.stats .wrap{grid-template-columns:1fr 1fr}.stat{min-height:140px}.features{grid-template-columns:1fr}.feature,.feature.small{min-height:380px}.feature-stack{grid-template-columns:1fr 1fr}.feature.small{min-height:240px}.section-head{display:block}.section-head .copy{margin-top:22px}.slider{grid-template-columns:1fr}.stage{min-height:0}.details{min-height:auto}.gallery-grid{grid-template-columns:1fr 1fr;grid-template-rows:290px 180px}.gallery-item:first-child{grid-column:1/3;grid-row:auto}.location{grid-template-columns:1fr}.location-image{min-height:330px;height:330px}.location-copy{padding:70px 30px}.footer-top,.footer-bottom{align-items:flex-start;flex-direction:column;gap:20px}}
    @media(max-width:490px){.wrap,.hero-content{width:calc(100% - 34px)}section{padding:90px 0}.hero h1{font-size:clamp(64px,17vw,102px)}.actions{align-items:stretch;flex-direction:column;gap:12px;max-width:270px}.hero-foot .wrap{flex-wrap:wrap;gap:8px}.quote{margin-left:15px;padding-left:27px}.feature-stack{grid-template-columns:1fr}.feature.small{min-height:260px}.amenity-list{grid-template-columns:1fr}.amenity:nth-child(odd){border-right:0;padding-right:0}.amenity:nth-child(even){padding-left:0}.gallery-grid{grid-template-columns:1fr;grid-template-rows:repeat(3,220px)}.gallery-item:first-child{grid-column:auto}.float{right:15px;bottom:15px;padding:13px 15px}.title{font-size:54px}}
  `;

  document.querySelector('link[href="style.css"]')?.remove();
  document.head.insertAdjacentHTML('beforeend', `<style>${css}</style>`);
  document.title = 'Santilana del Bosque | Tu lugar para volver a lo esencial';
  document.body.innerHTML = `
    <div class="top"><div class="wrap nav">
      <a class="brand" href="#inicio"><img src="img/logo.png" alt="Santilana del Bosque"></a>
      <button class="menu" aria-label="Abrir menú">☰</button>
      <nav class="links"><a href="#proyecto">El proyecto</a><a href="#amenidades">Amenidades</a><a href="#recorrido">Recorrido</a><a href="#ubicacion">Ubicación</a><a class="nav-cta" href="${wa('Hola, quiero conocer Santilana del Bosque')}">Hablemos →</a></nav>
    </div></div>
    <main>
      <section class="hero" id="inicio"><img src="img/hero.jpg" alt="Casa y paisaje de Santilana del Bosque"><div class="hero-content">
        <div class="eyebrow">Condominio natural · Puente Nacional, Santander</div><h1>Vuelve a<br><em>lo esencial.</em></h1><p>Un lugar para que el tiempo tenga otra medida. Lotes campestres donde la naturaleza no es el paisaje: es la forma de vivir.</p>
        <div class="actions"><a class="primary" href="${wa('Hola, quiero conocer Santilana del Bosque')}">Quiero conocerlo →</a><a class="ghost" href="#proyecto">Descubrir el proyecto ↘</a></div>
      </div><div class="hero-foot"><div class="wrap"><span>5° 52′ 21″ N · 73° 41′ 49″ O</span><span>Desliza para entrar</span><span>Una vida con más espacio</span></div></div></section>
      <section class="intro" id="proyecto"><div class="wrap intro-grid"><div><div class="eyebrow">El proyecto</div><h2 class="title">Un lugar para<br><em>volver a ti.</em></h2><p class="copy">Santilana del Bosque es un condominio natural para quienes quieren invertir en bienestar. Un lugar de casas de lujo, horizonte abierto y comunidad tranquila, a pocos minutos de todo lo que importa.</p></div><div class="quote">La naturaleza no es el paisaje:<br>es la forma de vivir.<small>— Santilana del Bosque</small></div></div></section>
      <div class="stats"><div class="wrap"><div class="stat"><strong>24K</strong><span>m² de zonas verdes</span></div><div class="stat"><strong>1K</strong><span>m² desde cada lote</span></div><div class="stat"><strong>24/7</strong><span>tranquilidad y seguridad</span></div><div class="stat"><strong>1</strong><span>forma más plena de vivir</span></div></div></div>
      <section class="experience"><div class="wrap"><div class="section-head"><div><div class="eyebrow">La experiencia</div><h2 class="title">Espacio para<br><em>lo que importa.</em></h2></div><p class="copy">Arquitectura, paisaje y calma se encuentran para crear un lugar que se disfruta todos los días.</p></div><div class="features"><article class="feature"><img src="img/casa.jpg" alt="Casa campestre rodeada de jardines"><div class="feature-copy"><small>Tu nuevo horizonte</small><h3>Construye la casa que imaginas.</h3></div></article><div class="feature-stack"><article class="feature small"><img src="img/piscina.jpg" alt="Piscina del proyecto"><div class="feature-copy"><small>Bienestar</small><h3>Rituales para bajar el ritmo.</h3></div></article><article class="feature small"><img src="img/hero.jpg" alt="Paisaje montañoso"><div class="feature-copy"><small>Entorno</small><h3>Montañas que siempre están.</h3></div></article></div></div></div></section>
      <section class="amenities" id="amenidades"><div class="wrap amenity-layout"><div><div class="eyebrow">El condominio</div><h2 class="title">Todo lo que<br><em>necesitas.</em></h2><p class="copy">Un entorno diseñado para vivir con más tiempo, más aire y más momentos compartidos.</p></div><div class="amenity-list">
        <div class="amenity"><b>◒</b><h3>Piscina social</h3><p>Un espacio para refrescarse y compartir sin prisa.</p></div><div class="amenity"><b>⌂</b><h3>Salón social</h3><p>Encuentros, celebraciones y comunidad.</p></div><div class="amenity"><b>♨</b><h3>Turco</h3><p>Bienestar y descanso para cerrar el día.</p></div><div class="amenity"><b>⌁</b><h3>Cancha de tenis</h3><p>Movimiento, juego y vida activa al aire libre.</p></div><div class="amenity"><b>♧</b><h3>Bosque nativo</h3><p>Naturaleza protegida como parte de tu cotidianidad.</p></div><div class="amenity"><b>✦</b><h3>Seguridad 24/7</h3><p>Acceso controlado para vivir con tranquilidad.</p></div>
      </div></div></section>
      <section class="plan"><div class="wrap plan-grid"><div><div class="eyebrow">Elige tu lugar</div><h2 class="title">Tu próximo<br><em>capítulo.</em></h2><p class="copy">Lotes desde 1.000 m² para construir una casa que se parezca a tu vida. Solicita el plano y conoce la disponibilidad actual.</p><a class="primary" href="${wa('Hola, quiero recibir el plano y la disponibilidad de los lotes')}">Solicitar disponibilidad →</a></div><div><div class="plan-frame"><img src="img/plano.jpg" alt="Plano general de Santilana del Bosque"></div><div class="caption"><span>Plano general</span><span>Santilana del Bosque</span></div></div></div></section>
      <section class="videos" id="recorrido"><div class="wrap"><div class="section-head"><div><div class="eyebrow">El recorrido</div><h2 class="title">Míralo desde<br><em>tu lugar.</em></h2></div><p class="copy">Conoce los espacios, las casas y la atmósfera del proyecto a través de nuestros videos.</p></div><div class="slider"><div class="stage"><video id="project-video" controls playsinline preload="metadata" poster="img/hero.jpg"><source src="videos/recorrido.mp4" type="video/mp4"></video><span class="badge">Video <span id="video-number">01</span> / 02</span></div><div class="details"><div><div class="num" id="video-index">01</div><h3 id="video-title">Recorre Santilana del Bosque</h3><p id="video-text">Conoce los espacios, las casas y la atmósfera del proyecto.</p></div><div class="controls"><button id="previous" aria-label="Video anterior">←</button><div class="dots"><button class="active" data-video="0" aria-label="Video 1"></button><button data-video="1" aria-label="Video 2"></button></div><button id="next" aria-label="Siguiente video">→</button></div></div></div></div></section>
      <section class="gallery"><div class="wrap"><div class="section-head"><div><div class="eyebrow">La galería</div><h2 class="title">Una mirada<br><em>más cerca.</em></h2></div><p class="copy">Cada detalle está pensado para que encuentres tu propia manera de habitar este lugar.</p></div><div class="gallery-grid"><div class="gallery-item"><img src="img/hero.jpg" alt="Vista panorámica del proyecto"></div><div class="gallery-item"><img src="img/casa.jpg" alt="Casa campestre"></div><div class="gallery-item"><img src="img/piscina.jpg" alt="Piscina y terraza"></div></div></div></section>
      <section class="location" id="ubicacion"><div class="location-image"><img src="img/hero.jpg" alt="Montañas de Santander"></div><div class="location-copy"><div class="eyebrow">La ubicación</div><h2 class="title">Cerca de todo.<br><em>Lejos del ruido.</em></h2><p class="copy">En Puente Nacional, Santander, encuentras el equilibrio entre conexión y calma. Un lugar para escapar sin alejarte de lo que importa.</p><div class="points"><div class="point"><strong>2 h 45 min</strong><span>Desde Bogotá</span></div><div class="point"><strong>40 min</strong><span>Desde Barbosa</span></div></div></div></section>
      <section class="contact" id="contacto"><div class="wrap contact-grid"><div><div class="eyebrow">Hablemos</div><h2 class="title">Tu lugar<br><em>te espera.</em></h2><p class="copy">Cuéntanos qué estás buscando. Te compartiremos disponibilidad, precios y todo lo necesario para dar el siguiente paso.</p></div><form class="form" id="contact-form"><label for="name">Tu nombre</label><input id="name" required placeholder="¿Cómo te llamas?"><label for="message">Mensaje</label><textarea id="message" required placeholder="Quiero conocer los lotes..."></textarea><button class="primary" type="submit">Enviar por WhatsApp →</button></form></div></section>
    </main>
    <footer><div class="wrap"><div class="footer-top"><a href="#inicio"><img class="footer-logo" src="img/logo.png" alt="Santilana del Bosque"></a><a class="phone" href="${wa('Hola, quiero información sobre Santilana del Bosque')}">+57 318 350 2235</a></div><div class="footer-bottom"><span>© 2026 Santilana del Bosque</span><span>Puente Nacional · Santander</span></div></div></footer>
    <a class="float" href="${wa('Hola, quiero información sobre Santilana del Bosque')}">◔ Escríbenos</a>
  `;

  const menu = document.querySelector('.menu');
  const links = document.querySelector('.links');
  menu?.addEventListener('click', () => links?.classList.toggle('open'));
  links?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => links.classList.remove('open')));

  const videos = [
    { src: 'videos/recorrido.mp4', title: 'Recorre Santilana del Bosque', text: 'Conoce los espacios, las casas y la atmósfera del proyecto.' },
    { src: 'videos/drone.mp4', title: 'Mira el proyecto desde arriba', text: 'Descubre la extensión del condominio y su paisaje de montañas.' }
  ];
  let active = 0;
  const video = document.querySelector('#project-video');
  const title = document.querySelector('#video-title');
  const text = document.querySelector('#video-text');
  const index = document.querySelector('#video-index');
  const number = document.querySelector('#video-number');
  const renderVideo = () => {
    const item = videos[active];
    video.src = item.src;
    title.textContent = item.title;
    text.textContent = item.text;
    index.textContent = number.textContent = String(active + 1).padStart(2, '0');
    document.querySelectorAll('.dots button').forEach((dot, i) => dot.classList.toggle('active', i === active));
  };
  document.querySelector('#previous')?.addEventListener('click', () => { active = (active + videos.length - 1) % videos.length; renderVideo(); });
  document.querySelector('#next')?.addEventListener('click', () => { active = (active + 1) % videos.length; renderVideo(); });
  document.querySelectorAll('.dots button').forEach((dot) => dot.addEventListener('click', () => { active = Number(dot.dataset.video); renderVideo(); }));
  document.querySelector('#contact-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const name = document.querySelector('#name').value.trim();
    const message = document.querySelector('#message').value.trim();
    window.open(wa(`Hola, soy ${name}. ${message}`), '_blank', 'noopener');
  });
})();